name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest

    permissions:
      contents: write

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: npm run electron:build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/**/*.exe